# Generated by Django 3.0.4 on 2020-03-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OuterFundWgConf',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('insert_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
