# Generated by Django 3.0.4 on 2020-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JqCodeInfo',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=150)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
