# Generated by Django 3.0.4 on 2020-04-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_jqcodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jqcodeinfo',
            name='jqcode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
