# Generated by Django 3.0.4 on 2020-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_fundclose'),
    ]

    operations = [
        migrations.CreateModel(
            name='jjCode',
            fields=[
                ('jjcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=100)),
                ('stype', models.CharField(max_length=50)),
                ('sday', models.DateField()),
                ('gm', models.FloatField()),
                ('insert_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='jjNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadate', models.DateField()),
                ('jjcode', models.CharField(max_length=20)),
                ('net_value', models.FloatField()),
                ('sum_value', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='jjTop10Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadate', models.DateField()),
                ('jjcode', models.CharField(max_length=20)),
                ('scode', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=100)),
                ('pct', models.FloatField()),
                ('num', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FundClose',
        ),
        migrations.DeleteModel(
            name='JqCodeInfo',
        ),
    ]
