# Generated by Django 3.0.4 on 2020-05-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20200514_1058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jjcode',
            table='ttjjcode',
        ),
        migrations.AlterModelTable(
            name='jjnet',
            table='ttjjnet',
        ),
        migrations.AlterModelTable(
            name='jjtop10stock',
            table='ttjjtop10stock',
        ),
    ]
